import { Figtree } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";

const figtree = Figtree({
  variable: "--font-figtree",
  subsets: ["latin"],
  display: 'swap',
});

export const metadata = {
  title: "Create Next App ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${figtree.className} font-figtree antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}